const INCREMENT_DICE_FACE = "INCREMENT_DICE_FACE";
const DECREMENT_DICE_FACE = "DECREMENT_DICE_FACE";
const INCREMENT_DICE_COUNT = "INCREMENT_DICE_COUNT";
const DECREMENT_DICE_COUNT = "DECREMENT_DICE_COUNT";
const SET_DICE_ROLL = "SET_DICE_ROLL"
const RESET = "RESET";

module.exports = {
    INCREMENT_DICE_FACE,
    DECREMENT_DICE_FACE,
    INCREMENT_DICE_COUNT,
    DECREMENT_DICE_COUNT,
    SET_DICE_ROLL,
    RESET
};
